disabled_rules:
  - function_parameter_count
  - type_body_length
  - type_name
  - function_body_length
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage  
